---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/home.yaml
  label: Titel
- type: document
  path: data/about.yaml
  label: Über Uns
- type: document
  path: data/contact.yaml
  label: Kontakt
- type: heading
  label: Content
- type: directory
  path: content/pages
  label: Seiten
  create: none
  match: "**/*"
  templates:
  - page
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
  templates:
  - team
- type: directory
  path: content/plays
  label: Stücke
  create: all
  match: "**/*"
  templates:
  - play
- type: directory
  path: content/events
  label: Veranstaltungen
  create: all
  match: "**/*"
  templates:
  - event
upload_dir: assets/uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.84.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.84.0
